<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\GeneralSetting;

class GeneralSettingSeeder extends Seeder
{
    public function run(): void
    {
        $settings = [
            // Site Branding
            [
                'key' => 'site_logo',
                'value' => null,
                'type' => 'image',
                'group' => 'branding',
                'label' => 'Site Logo',
                'description' => 'Main logo for the website (recommended: PNG with transparent background)',
                'sort_order' => 1,
            ],
            [
                'key' => 'site_favicon',
                'value' => null,
                'type' => 'image',
                'group' => 'branding',
                'label' => 'Site Favicon',
                'description' => 'Favicon for browser tabs (recommended: 32x32 or 64x64 PNG)',
                'sort_order' => 2,
            ],
            [
                'key' => 'site_og_image',
                'value' => null,
                'type' => 'image',
                'group' => 'branding',
                'label' => 'Default OG Image',
                'description' => 'Default Open Graph image for social media sharing (1200x630px recommended)',
                'sort_order' => 3,
            ],
            // Hero Section
            [
                'key' => 'hero_background_image',
                'value' => null,
                'type' => 'image',
                'group' => 'hero',
                'label' => 'Hero Background Image',
                'description' => 'Main background image for the hero section',
                'sort_order' => 1,
            ],
            [
                'key' => 'hero_title',
                'value' => 'Discover Myanmar\'s Finest Art',
                'type' => 'text',
                'group' => 'hero',
                'label' => 'Hero Title',
                'description' => 'Main headline text for the hero section',
                'sort_order' => 2,
            ],
            [
                'key' => 'hero_subtitle',
                'value' => 'Premium Art Marketplace',
                'type' => 'text',
                'group' => 'hero',
                'label' => 'Hero Subtitle',
                'description' => 'Subtitle text for the hero section',
                'sort_order' => 3,
            ],
            [
                'key' => 'hero_show_slider',
                'value' => '1',
                'type' => 'boolean',
                'group' => 'hero',
                'label' => 'Show Hero Slider',
                'description' => 'Enable/disable the hero image slider',
                'sort_order' => 4,
            ],
            // Banner Section
            [
                'key' => 'flash_sale_banner_image',
                'value' => null,
                'type' => 'image',
                'group' => 'banner',
                'label' => 'Flash Sale Banner Image',
                'description' => 'Background image for the flash sale banner',
                'sort_order' => 1,
            ],
            [
                'key' => 'flash_sale_enabled',
                'value' => '1',
                'type' => 'boolean',
                'group' => 'banner',
                'label' => 'Enable Flash Sale Banner',
                'description' => 'Show or hide the flash sale banner',
                'sort_order' => 2,
            ],
            [
                'key' => 'flash_sale_title',
                'value' => 'Limited Time Offer',
                'type' => 'text',
                'group' => 'banner',
                'label' => 'Flash Sale Title',
                'description' => 'Title text for the flash sale banner',
                'sort_order' => 3,
            ],
            // About Section
            [
                'key' => 'about_section_image',
                'value' => null,
                'type' => 'image',
                'group' => 'about',
                'label' => 'About Section Image',
                'description' => 'Featured image for the about section',
                'sort_order' => 1,
            ],
            [
                'key' => 'about_title',
                'value' => 'About Panchi Gallery',
                'type' => 'text',
                'group' => 'about',
                'label' => 'About Section Title',
                'description' => 'Title for the about section',
                'sort_order' => 2,
            ],
            [
                'key' => 'about_description',
                'value' => 'Your premier destination for authentic Myanmar art',
                'type' => 'textarea',
                'group' => 'about',
                'label' => 'About Description',
                'description' => 'Description text for the about section',
                'sort_order' => 3,
            ],
            // About Page Hero Section (Enhanced Hero Section)
            [
                'key' => 'about_hero_background_image',
                'value' => null,
                'type' => 'image',
                'group' => 'about_hero',
                'label' => 'About Hero Background Image',
                'description' => 'Background image for the about page hero section',
                'sort_order' => 1,
            ],
            [
                'key' => 'about_hero_title',
                'value' => "Bridging Myanmar Art\nwith the World",
                'type' => 'textarea',
                'group' => 'about_hero',
                'label' => 'About Hero Title',
                'description' => 'Main title for the about page hero section (use newline for line break)',
                'sort_order' => 2,
            ],
            [
                'key' => 'about_hero_subtitle_1',
                'value' => 'Where tradition meets contemporary expression',
                'type' => 'text',
                'group' => 'about_hero',
                'label' => 'About Hero Subtitle 1',
                'description' => 'First subtitle line for the about page hero',
                'sort_order' => 3,
            ],
            [
                'key' => 'about_hero_subtitle_2',
                'value' => 'Empowering Myanmar artists to reach global collectors',
                'type' => 'text',
                'group' => 'about_hero',
                'label' => 'About Hero Subtitle 2',
                'description' => 'Second subtitle line for the about page hero',
                'sort_order' => 4,
            ],
            [
                'key' => 'about_hero_description',
                'value' => 'Panchi Gallery is the premier destination for discovering and collecting authentic Myanmar art. We connect talented artists with art enthusiasts worldwide.',
                'type' => 'textarea',
                'group' => 'about_hero',
                'label' => 'About Hero Description',
                'description' => 'Description paragraph for the about page hero section',
                'sort_order' => 5,
            ],
            // About Page Mission Section (Enhanced Mission Section)
            [
                'key' => 'about_mission_section_image',
                'value' => null,
                'type' => 'image',
                'group' => 'about_mission',
                'label' => 'Mission Section Image',
                'description' => 'Image displayed in the mission section',
                'sort_order' => 1,
            ],
            [
                'key' => 'about_mission_badge',
                'value' => 'Our Mission',
                'type' => 'text',
                'group' => 'about_mission',
                'label' => 'Mission Badge Label',
                'description' => 'Small badge label above the mission title',
                'sort_order' => 2,
            ],
            [
                'key' => 'about_mission_title',
                'value' => 'Our Mission: Preserving & Promoting Myanmar Art',
                'type' => 'text',
                'group' => 'about_mission',
                'label' => 'Mission Title',
                'description' => 'Title for the mission section',
                'sort_order' => 3,
            ],
            [
                'key' => 'about_mission_p1',
                'value' => 'At Panchi Gallery, we are dedicated to preserving the rich artistic heritage of Myanmar while providing a global platform for contemporary artists to showcase their work.',
                'type' => 'textarea',
                'group' => 'about_mission',
                'label' => 'Mission Paragraph 1',
                'description' => 'First paragraph of the mission section',
                'sort_order' => 4,
            ],
            [
                'key' => 'about_mission_p2',
                'value' => 'We believe in the power of art to transcend borders and connect cultures. Every piece in our collection tells a story of tradition, innovation, and creative expression.',
                'type' => 'textarea',
                'group' => 'about_mission',
                'label' => 'Mission Paragraph 2',
                'description' => 'Second paragraph of the mission section',
                'sort_order' => 5,
            ],
            [
                'key' => 'about_mission_p3',
                'value' => 'Through verified certificates of authenticity and secure transactions, we ensure that every artwork you acquire is genuine and properly documented.',
                'type' => 'textarea',
                'group' => 'about_mission',
                'label' => 'Mission Paragraph 3',
                'description' => 'Third paragraph of the mission section',
                'sort_order' => 6,
            ],
            // Trust Badges / Secure Payment
            [
                'key' => 'secure_payment_badge_image',
                'value' => null,
                'type' => 'image',
                'group' => 'payment',
                'label' => 'Secure Payment Badge Image',
                'description' => 'Custom badge image for secure payment section',
                'sort_order' => 1,
            ],
            [
                'key' => 'show_trust_badges',
                'value' => '1',
                'type' => 'boolean',
                'group' => 'payment',
                'label' => 'Show Trust Badges',
                'description' => 'Show or hide the trust badges section',
                'sort_order' => 2,
            ],
            [
                'key' => 'platform_fee_percentage',
                'value' => '30',
                'type' => 'number',
                'group' => 'payment',
                'label' => 'Platform Fee Percentage',
                'description' => 'Commission percentage charged on each sale',
                'sort_order' => 3,
            ],
            [
                'key' => 'payment_gateways',
                'value' => '["stripe","paypal","kbzpay","wavepay"]',
                'type' => 'text',
                'group' => 'payment',
                'label' => 'Payment Gateways',
                'description' => 'Enabled payment gateways (JSON array)',
                'sort_order' => 4,
            ],
            // Currency Settings
            [
                'key' => 'default_currency',
                'value' => 'USD',
                'type' => 'select',
                'group' => 'currency',
                'label' => 'Default Currency',
                'description' => 'Default currency for the platform',
                'sort_order' => 1,
            ],
            [
                'key' => 'enabled_currencies',
                'value' => json_encode(['USD', 'MMK']),
                'type' => 'json',
                'group' => 'currency',
                'label' => 'Enabled Currencies',
                'description' => 'List of enabled currencies (JSON array: ["USD", "MMK"])',
                'sort_order' => 2,
            ],
            // Language Settings
            [
                'key' => 'default_language',
                'value' => 'en',
                'type' => 'select',
                'group' => 'language',
                'label' => 'Default Language',
                'description' => 'Default language for platform',
                'sort_order' => 1,
            ],
            [
                'key' => 'enabled_languages',
                'value' => json_encode(['en', 'my']),
                'type' => 'json',
                'group' => 'language',
                'label' => 'Enabled Languages',
                'description' => 'List of enabled languages (JSON array: ["en", "my"])',
                'sort_order' => 2,
            ],
            [
                'key' => 'auto_approve_payments',
                'value' => '0',
                'type' => 'boolean',
                'group' => 'payment',
                'label' => 'Auto Approve Payments',
                'description' => 'Automatically approve payment proofs',
                'sort_order' => 5,
            ],
            [
                'key' => 'auto_detect_language',
                'value' => '0',
                'type' => 'boolean',
                'group' => 'language',
                'label' => 'Auto-detect Language',
                'description' => 'Automatically detect user language from browser',
                'sort_order' => 3,
            ],
            // Shipping Settings
            [
                'key' => 'standard_shipping_cost',
                'value' => '15',
                'type' => 'number',
                'group' => 'shipping',
                'label' => 'Standard Shipping Cost',
                'description' => 'Cost for standard shipping in USD',
                'sort_order' => 1,
            ],
            [
                'key' => 'express_shipping_cost',
                'value' => '30',
                'type' => 'number',
                'group' => 'shipping',
                'label' => 'Express Shipping Cost',
                'description' => 'Cost for express shipping in USD',
                'sort_order' => 2,
            ],
            [
                'key' => 'free_shipping_threshold',
                'value' => '500',
                'type' => 'number',
                'group' => 'shipping',
                'label' => 'Free Shipping Threshold',
                'description' => 'Order amount threshold for free shipping in USD',
                'sort_order' => 3,
            ],
            [
                'key' => 'processing_days',
                'value' => '3',
                'type' => 'number',
                'group' => 'shipping',
                'label' => 'Processing Days',
                'description' => 'Days required to process orders before shipping',
                'sort_order' => 4,
            ],
            [
                'key' => 'international_enabled',
                'value' => '1',
                'type' => 'boolean',
                'group' => 'shipping',
                'label' => 'Enable International Shipping',
                'description' => 'Allow shipping to international destinations',
                'sort_order' => 5,
            ],
            // Backup Settings
            [
                'key' => 'backup_frequency',
                'value' => 'daily',
                'type' => 'select',
                'group' => 'backup',
                'label' => 'Backup Frequency',
                'description' => 'How often automatic backups should be created',
                'sort_order' => 1,
            ],
            [
                'key' => 'backup_retention',
                'value' => '30',
                'type' => 'number',
                'group' => 'backup',
                'label' => 'Backup Retention Period',
                'description' => 'Number of days to keep backup files',
                'sort_order' => 2,
            ],
            [
                'key' => 'last_backup',
                'value' => null,
                'type' => 'text',
                'group' => 'backup',
                'label' => 'Last Backup Timestamp',
                'description' => 'Timestamp of the last successful backup',
                'sort_order' => 3,
            ],
            // Cache Settings
            [
                'key' => 'cache_driver',
                'value' => 'file',
                'type' => 'select',
                'group' => 'cache',
                'label' => 'Cache Driver',
                'description' => 'Cache driver for the application',
                'sort_order' => 1,
            ],
            [
                'key' => 'cache_ttl',
                'value' => '60',
                'type' => 'number',
                'group' => 'cache',
                'label' => 'Cache TTL (Minutes)',
                'description' => 'Default time-to-live for cached items in minutes',
                'sort_order' => 2,
            ],
            [
                'key' => 'enable_page_cache',
                'value' => '0',
                'type' => 'boolean',
                'group' => 'cache',
                'label' => 'Enable Page Cache',
                'description' => 'Cache static pages for better performance',
                'sort_order' => 3,
            ],
        ];

        foreach ($settings as $setting) {
            GeneralSetting::updateOrCreate(
                ['key' => $setting['key']],
                $setting
            );
        }
    }
}
